// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHOCykYyOlrEmkF8TYDVdHv-r6xrIVzcA',
    appId:
        '1:518772064482:web:beec9fd936968038ff5ebb', // Note: Web appId might vary, but assuming consistent prefix
    messagingSenderId: '518772064482',
    projectId: 'kid-86bbc',
    authDomain: 'kid-86bbc.firebaseapp.com',
    storageBucket: 'kid-86bbc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHOCykYyOlrEmkF8TYDVdHv-r6xrIVzcA',
    appId: '1:518772064482:android:8d350c7090ede322ff5ebb',
    messagingSenderId: '518772064482',
    projectId: 'kid-86bbc',
    storageBucket: 'kid-86bbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHOCykYyOlrEmkF8TYDVdHv-r6xrIVzcA',
    appId:
        '1:518772064482:ios:76d456de98877526ff5ebb', // Note: iOS appId might vary
    messagingSenderId: '518772064482',
    projectId: 'kid-86bbc',
    storageBucket: 'kid-86bbc.firebasestorage.app',
    iosBundleId: 'com.example.kidsecure',
  );
}
